import type { Token } from '../types';

// Popular tokens with their metadata
export const POPULAR_TOKENS: Token[] = [
  {
    symbol: 'ETH',
    name: 'Ethereum',
    decimals: 18,
    logoURI: '/src/assets/tokens/ETH.svg',
    chainId: 1,
  },
  {
    symbol: 'USDC',
    name: 'USD Coin',
    decimals: 6,
    logoURI: '/src/assets/tokens/USDC.svg',
    chainId: 1,
  },
  {
    symbol: 'USDT',
    name: 'Tether USD',
    decimals: 6,
    logoURI: '/src/assets/tokens/USDT.svg',
    chainId: 1,
  },
  {
    symbol: 'WBTC',
    name: 'Wrapped Bitcoin',
    decimals: 8,
    logoURI: '/src/assets/tokens/WBTC.svg',
    chainId: 1,
  },
  {
    symbol: 'ATOM',
    name: 'Cosmos',
    decimals: 6,
    logoURI: '/src/assets/tokens/ATOM.svg',
    chainId: 1,
  },
  {
    symbol: 'OSMO',
    name: 'Osmosis',
    decimals: 6,
    logoURI: '/src/assets/tokens/OSMO.svg',
    chainId: 1,
  },
  {
    symbol: 'LUNA',
    name: 'Terra',
    decimals: 6,
    logoURI: '/src/assets/tokens/LUNA.svg',
    chainId: 1,
  },
  {
    symbol: 'KUJI',
    name: 'Kujira',
    decimals: 6,
    logoURI: '/src/assets/tokens/KUJI.svg',
    chainId: 1,
  },
  {
    symbol: 'EVMOS',
    name: 'Evmos',
    decimals: 18,
    logoURI: '/src/assets/tokens/EVMOS.svg',
    chainId: 1,
  },
  {
    symbol: 'STRD',
    name: 'Stride',
    decimals: 6,
    logoURI: '/src/assets/tokens/STRD.svg',
    chainId: 1,
  },
  {
    symbol: 'IBCX',
    name: 'IBCX',
    decimals: 6,
    logoURI: '/src/assets/tokens/IBCX.svg',
    chainId: 1,
  },
  {
    symbol: 'IRIS',
    name: 'IRISnet',
    decimals: 6,
    logoURI: '/src/assets/tokens/IRIS.svg',
    chainId: 1,
  },
  {
    symbol: 'RATOM',
    name: 'RATOM',
    decimals: 6,
    logoURI: '/src/assets/tokens/rATOM.svg',
    chainId: 1,
  },
  {
    symbol: 'STATOM',
    name: 'stATOM',
    decimals: 6,
    logoURI: '/src/assets/tokens/STATOM.svg',
    chainId: 1,
  },
  {
    symbol: 'STLUNA',
    name: 'stLUNA',
    decimals: 6,
    logoURI: '/src/assets/tokens/STLUNA.svg',
    chainId: 1,
  },
  {
    symbol: 'STOSMO',
    name: 'stOSMO',
    decimals: 6,
    logoURI: '/src/assets/tokens/STOSMO.svg',
    chainId: 1,
  },
  {
    symbol: 'STEVMOS',
    name: 'stEVMOS',
    decimals: 18,
    logoURI: '/src/assets/tokens/STEVMOS.svg',
    chainId: 1,
  },
  {
    symbol: 'ampLUNA',
    name: 'ampLUNA',
    decimals: 6,
    logoURI: '/src/assets/tokens/ampLUNA.svg',
    chainId: 1,
  },
  {
    symbol: 'axlUSDC',
    name: 'Axelar USDC',
    decimals: 6,
    logoURI: '/src/assets/tokens/axlUSDC.svg',
    chainId: 1,
  },
  {
    symbol: 'rSWTH',
    name: 'rSWTH',
    decimals: 8,
    logoURI: '/src/assets/tokens/rSWTH.svg',
    chainId: 1,
  },
  {
    symbol: 'LSI',
    name: 'Liquid Staking Index',
    decimals: 6,
    logoURI: '/src/assets/tokens/LSI.svg',
    chainId: 1,
  },
  {
    symbol: 'OKB',
    name: 'OKB',
    decimals: 18,
    logoURI: '/src/assets/tokens/OKB.svg',
    chainId: 1,
  },
  {
    symbol: 'OKT',
    name: 'OKT',
    decimals: 18,
    logoURI: '/src/assets/tokens/OKT.svg',
    chainId: 1,
  },
  {
    symbol: 'SWTH',
    name: 'Switcheo',
    decimals: 8,
    logoURI: '/src/assets/tokens/SWTH.svg',
    chainId: 1,
  },
  {
    symbol: 'USC',
    name: 'USC',
    decimals: 6,
    logoURI: '/src/assets/tokens/USC.svg',
    chainId: 1,
  },
  {
    symbol: 'wstETH',
    name: 'Wrapped stETH',
    decimals: 18,
    logoURI: '/src/assets/tokens/wstETH.svg',
    chainId: 1,
  },
  {
    symbol: 'YieldUSD',
    name: 'YieldUSD',
    decimals: 6,
    logoURI: '/src/assets/tokens/YieldUSD.svg',
    chainId: 1,
  },
  {
    symbol: 'ZIL',
    name: 'Zilliqa',
    decimals: 12,
    logoURI: '/src/assets/tokens/ZIL.svg',
    chainId: 1,
  },
  {
    symbol: 'BLUR',
    name: 'Blur',
    decimals: 18,
    logoURI: '/src/assets/tokens/BLUR.svg',
    chainId: 1,
  },
  {
    symbol: 'bNEO',
    name: 'bNEO',
    decimals: 8,
    logoURI: '/src/assets/tokens/bNEO.svg',
    chainId: 1,
  },
  {
    symbol: 'BUSD',
    name: 'Binance USD',
    decimals: 18,
    logoURI: '/src/assets/tokens/BUSD.svg',
    chainId: 1,
  },
  {
    symbol: 'GMX',
    name: 'GMX',
    decimals: 18,
    logoURI: '/src/assets/tokens/GMX.svg',
    chainId: 1,
  },
  // Additional tokens for infinite scroll demo
  {
    symbol: 'AAVE',
    name: 'Aave Token',
    decimals: 18,
    logoURI: '/src/assets/tokens/AAVE.svg',
    chainId: 1,
  },
  {
    symbol: 'UNI',
    name: 'Uniswap',
    decimals: 18,
    logoURI: '/src/assets/tokens/UNI.svg',
    chainId: 1,
  },
  {
    symbol: 'LINK',
    name: 'Chainlink',
    decimals: 18,
    logoURI: '/src/assets/tokens/LINK.svg',
    chainId: 1,
  },
  {
    symbol: 'MATIC',
    name: 'Polygon',
    decimals: 18,
    logoURI: '/src/assets/tokens/MATIC.svg',
    chainId: 1,
  },
  {
    symbol: 'AVAX',
    name: 'Avalanche',
    decimals: 18,
    logoURI: '/src/assets/tokens/AVAX.svg',
    chainId: 1,
  },
  {
    symbol: 'SOL',
    name: 'Solana',
    decimals: 9,
    logoURI: '/src/assets/tokens/SOL.svg',
    chainId: 1,
  },
  {
    symbol: 'DOT',
    name: 'Polkadot',
    decimals: 10,
    logoURI: '/src/assets/tokens/DOT.svg',
    chainId: 1,
  },
  {
    symbol: 'ADA',
    name: 'Cardano',
    decimals: 6,
    logoURI: '/src/assets/tokens/ADA.svg',
    chainId: 1,
  },
  {
    symbol: 'XRP',
    name: 'Ripple',
    decimals: 6,
    logoURI: '/src/assets/tokens/XRP.svg',
    chainId: 1,
  },
  {
    symbol: 'DOGE',
    name: 'Dogecoin',
    decimals: 8,
    logoURI: '/src/assets/tokens/DOGE.svg',
    chainId: 1,
  },
  {
    symbol: 'SHIB',
    name: 'Shiba Inu',
    decimals: 18,
    logoURI: '/src/assets/tokens/SHIB.svg',
    chainId: 1,
  },
  {
    symbol: 'LTC',
    name: 'Litecoin',
    decimals: 8,
    logoURI: '/src/assets/tokens/LTC.svg',
    chainId: 1,
  },
  {
    symbol: 'BCH',
    name: 'Bitcoin Cash',
    decimals: 8,
    logoURI: '/src/assets/tokens/BCH.svg',
    chainId: 1,
  },
  {
    symbol: 'ALGO',
    name: 'Algorand',
    decimals: 6,
    logoURI: '/src/assets/tokens/ALGO.svg',
    chainId: 1,
  },
  {
    symbol: 'VET',
    name: 'VeChain',
    decimals: 18,
    logoURI: '/src/assets/tokens/VET.svg',
    chainId: 1,
  },
  {
    symbol: 'FIL',
    name: 'Filecoin',
    decimals: 18,
    logoURI: '/src/assets/tokens/FIL.svg',
    chainId: 1,
  },
  {
    symbol: 'TRX',
    name: 'TRON',
    decimals: 6,
    logoURI: '/src/assets/tokens/TRX.svg',
    chainId: 1,
  },
  {
    symbol: 'EOS',
    name: 'EOS',
    decimals: 4,
    logoURI: '/src/assets/tokens/EOS.svg',
    chainId: 1,
  },
  {
    symbol: 'XLM',
    name: 'Stellar',
    decimals: 7,
    logoURI: '/src/assets/tokens/XLM.svg',
    chainId: 1,
  },
  {
    symbol: 'XTZ',
    name: 'Tezos',
    decimals: 6,
    logoURI: '/src/assets/tokens/XTZ.svg',
    chainId: 1,
  },
  {
    symbol: 'NEO',
    name: 'NEO',
    decimals: 8,
    logoURI: '/src/assets/tokens/NEO.svg',
    chainId: 1,
  },
  {
    symbol: 'IOTA',
    name: 'IOTA',
    decimals: 6,
    logoURI: '/src/assets/tokens/IOTA.svg',
    chainId: 1,
  },
  {
    symbol: 'DASH',
    name: 'Dash',
    decimals: 8,
    logoURI: '/src/assets/tokens/DASH.svg',
    chainId: 1,
  },
  {
    symbol: 'ZEC',
    name: 'Zcash',
    decimals: 8,
    logoURI: '/src/assets/tokens/ZEC.svg',
    chainId: 1,
  },
  {
    symbol: 'COMP',
    name: 'Compound',
    decimals: 18,
    logoURI: '/src/assets/tokens/COMP.svg',
    chainId: 1,
  },
  {
    symbol: 'MKR',
    name: 'Maker',
    decimals: 18,
    logoURI: '/src/assets/tokens/MKR.svg',
    chainId: 1,
  },
  {
    symbol: 'SNX',
    name: 'Synthetix',
    decimals: 18,
    logoURI: '/src/assets/tokens/SNX.svg',
    chainId: 1,
  },
  {
    symbol: 'YFI',
    name: 'Yearn Finance',
    decimals: 18,
    logoURI: '/src/assets/tokens/YFI.svg',
    chainId: 1,
  },
  {
    symbol: 'SUSHI',
    name: 'SushiSwap',
    decimals: 18,
    logoURI: '/src/assets/tokens/SUSHI.svg',
    chainId: 1,
  },
  {
    symbol: 'CRV',
    name: 'Curve DAO Token',
    decimals: 18,
    logoURI: '/src/assets/tokens/CRV.svg',
    chainId: 1,
  },
  {
    symbol: '1INCH',
    name: '1inch',
    decimals: 18,
    logoURI: '/src/assets/tokens/1INCH.svg',
    chainId: 1,
  },
  {
    symbol: 'BAL',
    name: 'Balancer',
    decimals: 18,
    logoURI: '/src/assets/tokens/BAL.svg',
    chainId: 1,
  },
  {
    symbol: 'LRC',
    name: 'Loopring',
    decimals: 18,
    logoURI: '/src/assets/tokens/LRC.svg',
    chainId: 1,
  },
  {
    symbol: 'ZRX',
    name: '0x Protocol',
    decimals: 18,
    logoURI: '/src/assets/tokens/ZRX.svg',
    chainId: 1,
  },
  {
    symbol: 'BAT',
    name: 'Basic Attention Token',
    decimals: 18,
    logoURI: '/src/assets/tokens/BAT.svg',
    chainId: 1,
  },
  {
    symbol: 'ENJ',
    name: 'Enjin Coin',
    decimals: 18,
    logoURI: '/src/assets/tokens/ENJ.svg',
    chainId: 1,
  },
  {
    symbol: 'MANA',
    name: 'Decentraland',
    decimals: 18,
    logoURI: '/src/assets/tokens/MANA.svg',
    chainId: 1,
  },
  {
    symbol: 'SAND',
    name: 'The Sandbox',
    decimals: 18,
    logoURI: '/src/assets/tokens/SAND.svg',
    chainId: 1,
  },
  {
    symbol: 'AXS',
    name: 'Axie Infinity',
    decimals: 18,
    logoURI: '/src/assets/tokens/AXS.svg',
    chainId: 1,
  },
  {
    symbol: 'CHZ',
    name: 'Chiliz',
    decimals: 18,
    logoURI: '/src/assets/tokens/CHZ.svg',
    chainId: 1,
  },
  {
    symbol: 'FLOW',
    name: 'Flow',
    decimals: 8,
    logoURI: '/src/assets/tokens/FLOW.svg',
    chainId: 1,
  },
  {
    symbol: 'ICP',
    name: 'Internet Computer',
    decimals: 8,
    logoURI: '/src/assets/tokens/ICP.svg',
    chainId: 1,
  },
  {
    symbol: 'THETA',
    name: 'Theta Network',
    decimals: 18,
    logoURI: '/src/assets/tokens/THETA.svg',
    chainId: 1,
  },
  {
    symbol: 'FTM',
    name: 'Fantom',
    decimals: 18,
    logoURI: '/src/assets/tokens/FTM.svg',
    chainId: 1,
  },
  {
    symbol: 'NEAR',
    name: 'NEAR Protocol',
    decimals: 24,
    logoURI: '/src/assets/tokens/NEAR.svg',
    chainId: 1,
  },
  {
    symbol: 'HBAR',
    name: 'Hedera',
    decimals: 8,
    logoURI: '/src/assets/tokens/HBAR.svg',
    chainId: 1,
  },
  {
    symbol: 'EGLD',
    name: 'MultiversX',
    decimals: 18,
    logoURI: '/src/assets/tokens/EGLD.svg',
    chainId: 1,
  },
  {
    symbol: 'KLAY',
    name: 'Klaytn',
    decimals: 18,
    logoURI: '/src/assets/tokens/KLAY.svg',
    chainId: 1,
  },
  {
    symbol: 'FTT',
    name: 'FTX Token',
    decimals: 18,
    logoURI: '/src/assets/tokens/FTT.svg',
    chainId: 1,
  },
  {
    symbol: 'CRO',
    name: 'Cronos',
    decimals: 8,
    logoURI: '/src/assets/tokens/CRO.svg',
    chainId: 1,
  },
  {
    symbol: 'KCS',
    name: 'KuCoin Token',
    decimals: 6,
    logoURI: '/src/assets/tokens/KCS.svg',
    chainId: 1,
  },
  {
    symbol: 'HT',
    name: 'Huobi Token',
    decimals: 18,
    logoURI: '/src/assets/tokens/HT.svg',
    chainId: 1,
  },
  {
    symbol: 'LEO',
    name: 'LEO Token',
    decimals: 18,
    logoURI: '/src/assets/tokens/LEO.svg',
    chainId: 1,
  },
  {
    symbol: 'GT',
    name: 'GateToken',
    decimals: 18,
    logoURI: '/src/assets/tokens/GT.svg',
    chainId: 1,
  },
  {
    symbol: 'BNB',
    name: 'BNB',
    decimals: 18,
    logoURI: '/src/assets/tokens/BNB.svg',
    chainId: 1,
  },
  {
    symbol: 'CAKE',
    name: 'PancakeSwap',
    decimals: 18,
    logoURI: '/src/assets/tokens/CAKE.svg',
    chainId: 1,
  },
  {
    symbol: 'BAKE',
    name: 'BakeryToken',
    decimals: 18,
    logoURI: '/src/assets/tokens/BAKE.svg',
    chainId: 1,
  },
  {
    symbol: 'AUTO',
    name: 'AutoFarm',
    decimals: 18,
    logoURI: '/src/assets/tokens/AUTO.svg',
    chainId: 1,
  },
  {
    symbol: 'ALPHA',
    name: 'Alpha Finance',
    decimals: 18,
    logoURI: '/src/assets/tokens/ALPHA.svg',
    chainId: 1,
  },
  {
    symbol: 'BAND',
    name: 'Band Protocol',
    decimals: 18,
    logoURI: '/src/assets/tokens/BAND.svg',
    chainId: 1,
  },
  {
    symbol: 'KAVA',
    name: 'Kava',
    decimals: 6,
    logoURI: '/src/assets/tokens/KAVA.svg',
    chainId: 1,
  },
  {
    symbol: 'RUNE',
    name: 'THORChain',
    decimals: 8,
    logoURI: '/src/assets/tokens/RUNE.svg',
    chainId: 1,
  },
  {
    symbol: 'ROSE',
    name: 'Oasis Network',
    decimals: 8,
    logoURI: '/src/assets/tokens/ROSE.svg',
    chainId: 1,
  },
  {
    symbol: 'SCRT',
    name: 'Secret Network',
    decimals: 6,
    logoURI: '/src/assets/tokens/SCRT.svg',
    chainId: 1,
  },
  {
    symbol: 'JUNO',
    name: 'Juno Network',
    decimals: 6,
    logoURI: '/src/assets/tokens/JUNO.svg',
    chainId: 1,
  },
  {
    symbol: 'STARS',
    name: 'Stargaze',
    decimals: 6,
    logoURI: '/src/assets/tokens/STARS.svg',
    chainId: 1,
  },
  {
    symbol: 'REGEN',
    name: 'Regen Network',
    decimals: 6,
    logoURI: '/src/assets/tokens/REGEN.svg',
    chainId: 1,
  },
  {
    symbol: 'AKASH',
    name: 'Akash Network',
    decimals: 6,
    logoURI: '/src/assets/tokens/AKASH.svg',
    chainId: 1,
  },
  {
    symbol: 'SENT',
    name: 'Sentinel',
    decimals: 6,
    logoURI: '/src/assets/tokens/SENT.svg',
    chainId: 1,
  },
  {
    symbol: 'FET',
    name: 'Fetch.ai',
    decimals: 18,
    logoURI: '/src/assets/tokens/FET.svg',
    chainId: 1,
  },
  {
    symbol: 'PERSISTENCE',
    name: 'Persistence',
    decimals: 6,
    logoURI: '/src/assets/tokens/PERSISTENCE.svg',
    chainId: 1,
  },
  {
    symbol: 'CRYPTO',
    name: 'Crypto.com Coin',
    decimals: 8,
    logoURI: '/src/assets/tokens/CRYPTO.svg',
    chainId: 1,
  },
  {
    symbol: 'CEL',
    name: 'Celsius',
    decimals: 4,
    logoURI: '/src/assets/tokens/CEL.svg',
    chainId: 1,
  },
  {
    symbol: 'NEXO',
    name: 'NEXO',
    decimals: 18,
    logoURI: '/src/assets/tokens/NEXO.svg',
    chainId: 1,
  },
  {
    symbol: 'COMPOUND',
    name: 'Compound',
    decimals: 18,
    logoURI: '/src/assets/tokens/COMPOUND.svg',
    chainId: 1,
  },
  {
    symbol: 'UMA',
    name: 'UMA',
    decimals: 18,
    logoURI: '/src/assets/tokens/UMA.svg',
    chainId: 1,
  },
  {
    symbol: 'REN',
    name: 'Ren',
    decimals: 18,
    logoURI: '/src/assets/tokens/REN.svg',
    chainId: 1,
  },
  {
    symbol: 'KNC',
    name: 'Kyber Network',
    decimals: 18,
    logoURI: '/src/assets/tokens/KNC.svg',
    chainId: 1,
  },
  {
    symbol: 'REP',
    name: 'Augur',
    decimals: 18,
    logoURI: '/src/assets/tokens/REP.svg',
    chainId: 1,
  },
  {
    symbol: 'LEND',
    name: 'Aave LEND',
    decimals: 18,
    logoURI: '/src/assets/tokens/LEND.svg',
    chainId: 1,
  },
  {
    symbol: 'KEEP',
    name: 'Keep Network',
    decimals: 18,
    logoURI: '/src/assets/tokens/KEEP.svg',
    chainId: 1,
  },
  {
    symbol: 'NU',
    name: 'NuCypher',
    decimals: 18,
    logoURI: '/src/assets/tokens/NU.svg',
    chainId: 1,
  },
  {
    symbol: 'STORJ',
    name: 'Storj',
    decimals: 8,
    logoURI: '/src/assets/tokens/STORJ.svg',
    chainId: 1,
  },
  {
    symbol: 'GNO',
    name: 'Gnosis',
    decimals: 18,
    logoURI: '/src/assets/tokens/GNO.svg',
    chainId: 1,
  },
  {
    symbol: 'ANT',
    name: 'Aragon',
    decimals: 18,
    logoURI: '/src/assets/tokens/ANT.svg',
    chainId: 1,
  },
  {
    symbol: 'MLN',
    name: 'Melon',
    decimals: 18,
    logoURI: '/src/assets/tokens/MLN.svg',
    chainId: 1,
  },
  {
    symbol: 'DGX',
    name: 'Digix Gold',
    decimals: 9,
    logoURI: '/src/assets/tokens/DGX.svg',
    chainId: 1,
  },
  {
    symbol: 'MKR',
    name: 'Maker',
    decimals: 18,
    logoURI: '/src/assets/tokens/MKR.svg',
    chainId: 1,
  },
  {
    symbol: 'DAI',
    name: 'Dai Stablecoin',
    decimals: 18,
    logoURI: '/src/assets/tokens/DAI.svg',
    chainId: 1,
  },
  {
    symbol: 'SAI',
    name: 'Sai Stablecoin',
    decimals: 18,
    logoURI: '/src/assets/tokens/SAI.svg',
    chainId: 1,
  },
  {
    symbol: 'USDS',
    name: 'USD//C',
    decimals: 6,
    logoURI: '/src/assets/tokens/USDS.svg',
    chainId: 1,
  },
  {
    symbol: 'TUSD',
    name: 'TrueUSD',
    decimals: 18,
    logoURI: '/src/assets/tokens/TUSD.svg',
    chainId: 1,
  },
  {
    symbol: 'GUSD',
    name: 'Gemini Dollar',
    decimals: 2,
    logoURI: '/src/assets/tokens/GUSD.svg',
    chainId: 1,
  },
  {
    symbol: 'PAX',
    name: 'Paxos Standard',
    decimals: 18,
    logoURI: '/src/assets/tokens/PAX.svg',
    chainId: 1,
  },
  {
    symbol: 'BUSD',
    name: 'Binance USD',
    decimals: 18,
    logoURI: '/src/assets/tokens/BUSD.svg',
    chainId: 1,
  },
  {
    symbol: 'HUSD',
    name: 'HUSD',
    decimals: 8,
    logoURI: '/src/assets/tokens/HUSD.svg',
    chainId: 1,
  },
  {
    symbol: 'USDN',
    name: 'Neutrino USD',
    decimals: 6,
    logoURI: '/src/assets/tokens/USDN.svg',
    chainId: 1,
  },
  {
    symbol: 'RSV',
    name: 'Reserve',
    decimals: 18,
    logoURI: '/src/assets/tokens/RSV.svg',
    chainId: 1,
  },
  {
    symbol: 'FRAX',
    name: 'Frax',
    decimals: 18,
    logoURI: '/src/assets/tokens/FRAX.svg',
    chainId: 1,
  },
  {
    symbol: 'LUSD',
    name: 'Liquity USD',
    decimals: 18,
    logoURI: '/src/assets/tokens/LUSD.svg',
    chainId: 1,
  },
  {
    symbol: 'FEI',
    name: 'Fei USD',
    decimals: 18,
    logoURI: '/src/assets/tokens/FEI.svg',
    chainId: 1,
  },
  {
    symbol: 'TRIBE',
    name: 'Tribe',
    decimals: 18,
    logoURI: '/src/assets/tokens/TRIBE.svg',
    chainId: 1,
  },
  {
    symbol: 'RAI',
    name: 'Rai Reflex Index',
    decimals: 18,
    logoURI: '/src/assets/tokens/RAI.svg',
    chainId: 1,
  },
  {
    symbol: 'ALUSD',
    name: 'Alchemix USD',
    decimals: 18,
    logoURI: '/src/assets/tokens/ALUSD.svg',
    chainId: 1,
  },
  {
    symbol: 'DOLA',
    name: 'Dola USD Stablecoin',
    decimals: 18,
    logoURI: '/src/assets/tokens/DOLA.svg',
    chainId: 1,
  },
  {
    symbol: 'OHM',
    name: 'Olympus',
    decimals: 9,
    logoURI: '/src/assets/tokens/OHM.svg',
    chainId: 1,
  },
  {
    symbol: 'SPELL',
    name: 'Spell Token',
    decimals: 18,
    logoURI: '/src/assets/tokens/SPELL.svg',
    chainId: 1,
  },
  {
    symbol: 'MIM',
    name: 'Magic Internet Money',
    decimals: 18,
    logoURI: '/src/assets/tokens/MIM.svg',
    chainId: 1,
  },
  {
    symbol: 'CVX',
    name: 'Convex Finance',
    decimals: 18,
    logoURI: '/src/assets/tokens/CVX.svg',
    chainId: 1,
  },
  {
    symbol: 'FXS',
    name: 'Frax Share',
    decimals: 18,
    logoURI: '/src/assets/tokens/FXS.svg',
    chainId: 1,
  },
  {
    symbol: 'LQTY',
    name: 'Liquity',
    decimals: 18,
    logoURI: '/src/assets/tokens/LQTY.svg',
    chainId: 1,
  },
  {
    symbol: 'ALCX',
    name: 'Alchemix',
    decimals: 18,
    logoURI: '/src/assets/tokens/ALCX.svg',
    chainId: 1,
  },
  {
    symbol: 'TOKE',
    name: 'Tokemak',
    decimals: 18,
    logoURI: '/src/assets/tokens/TOKE.svg',
    chainId: 1,
  },
  {
    symbol: 'BTRFLY',
    name: 'Redacted Cartel',
    decimals: 18,
    logoURI: '/src/assets/tokens/BTRFLY.svg',
    chainId: 1,
  },
  {
    symbol: 'PENDLE',
    name: 'Pendle',
    decimals: 18,
    logoURI: '/src/assets/tokens/PENDLE.svg',
    chainId: 1,
  },
  {
    symbol: 'ANGLE',
    name: 'Angle Protocol',
    decimals: 18,
    logoURI: '/src/assets/tokens/ANGLE.svg',
    chainId: 1,
  },
  {
    symbol: 'FARM',
    name: 'Harvest Finance',
    decimals: 18,
    logoURI: '/src/assets/tokens/FARM.svg',
    chainId: 1,
  },
  {
    symbol: 'PICKLE',
    name: 'Pickle Finance',
    decimals: 18,
    logoURI: '/src/assets/tokens/PICKLE.svg',
    chainId: 1,
  },
  {
    symbol: 'CREAM',
    name: 'Cream Finance',
    decimals: 18,
    logoURI: '/src/assets/tokens/CREAM.svg',
    chainId: 1,
  },
  {
    symbol: 'ALPHA',
    name: 'Alpha Homora',
    decimals: 18,
    logoURI: '/src/assets/tokens/ALPHA.svg',
    chainId: 1,
  },
  {
    symbol: 'BETA',
    name: 'Beta Finance',
    decimals: 18,
    logoURI: '/src/assets/tokens/BETA.svg',
    chainId: 1,
  },
  {
    symbol: 'GAMMA',
    name: 'Gamma Protocol',
    decimals: 18,
    logoURI: '/src/assets/tokens/GAMMA.svg',
    chainId: 1,
  },
  {
    symbol: 'DELTA',
    name: 'Delta Protocol',
    decimals: 18,
    logoURI: '/src/assets/tokens/DELTA.svg',
    chainId: 1,
  },
  {
    symbol: 'THETA',
    name: 'Theta Protocol',
    decimals: 18,
    logoURI: '/src/assets/tokens/THETA.svg',
    chainId: 1,
  },
  {
    symbol: 'LAMBDA',
    name: 'Lambda Protocol',
    decimals: 18,
    logoURI: '/src/assets/tokens/LAMBDA.svg',
    chainId: 1,
  },
  {
    symbol: 'SIGMA',
    name: 'Sigma Protocol',
    decimals: 18,
    logoURI: '/src/assets/tokens/SIGMA.svg',
    chainId: 1,
  },
  {
    symbol: 'OMEGA',
    name: 'Omega Protocol',
    decimals: 18,
    logoURI: '/src/assets/tokens/OMEGA.svg',
    chainId: 1,
  },
  {
    symbol: 'PHI',
    name: 'Phi Protocol',
    decimals: 18,
    logoURI: '/src/assets/tokens/PHI.svg',
    chainId: 1,
  },
  {
    symbol: 'PSI',
    name: 'Psi Protocol',
    decimals: 18,
    logoURI: '/src/assets/tokens/PSI.svg',
    chainId: 1,
  },
  {
    symbol: 'CHI',
    name: 'Chi Protocol',
    decimals: 18,
    logoURI: '/src/assets/tokens/CHI.svg',
    chainId: 1,
  },
  {
    symbol: 'XI',
    name: 'Xi Protocol',
    decimals: 18,
    logoURI: '/src/assets/tokens/XI.svg',
    chainId: 1,
  },
  {
    symbol: 'RHO',
    name: 'Rho Protocol',
    decimals: 18,
    logoURI: '/src/assets/tokens/RHO.svg',
    chainId: 1,
  },
  {
    symbol: 'TAU',
    name: 'Tau Protocol',
    decimals: 18,
    logoURI: '/src/assets/tokens/TAU.svg',
    chainId: 1,
  },
  {
    symbol: 'UPSILON',
    name: 'Upsilon Protocol',
    decimals: 18,
    logoURI: '/src/assets/tokens/UPSILON.svg',
    chainId: 1,
  },
  {
    symbol: 'PHI2',
    name: 'Phi2 Protocol',
    decimals: 18,
    logoURI: '/src/assets/tokens/PHI2.svg',
    chainId: 1,
  },
  {
    symbol: 'CHI2',
    name: 'Chi2 Protocol',
    decimals: 18,
    logoURI: '/src/assets/tokens/CHI2.svg',
    chainId: 1,
  },
  {
    symbol: 'PSI2',
    name: 'Psi2 Protocol',
    decimals: 18,
    logoURI: '/src/assets/tokens/PSI2.svg',
    chainId: 1,
  },
  {
    symbol: 'OMEGA2',
    name: 'Omega2 Protocol',
    decimals: 18,
    logoURI: '/src/assets/tokens/OMEGA2.svg',
    chainId: 1,
  },
  {
    symbol: 'SIGMA2',
    name: 'Sigma2 Protocol',
    decimals: 18,
    logoURI: '/src/assets/tokens/SIGMA2.svg',
    chainId: 1,
  },
  {
    symbol: 'TAU2',
    name: 'Tau2 Protocol',
    decimals: 18,
    logoURI: '/src/assets/tokens/TAU2.svg',
    chainId: 1,
  },
  {
    symbol: 'UPSILON2',
    name: 'Upsilon2 Protocol',
    decimals: 18,
    logoURI: '/src/assets/tokens/UPSILON2.svg',
    chainId: 1,
  },
  {
    symbol: 'PHI3',
    name: 'Phi3 Protocol',
    decimals: 18,
    logoURI: '/src/assets/tokens/PHI3.svg',
    chainId: 1,
  },
  {
    symbol: 'CHI3',
    name: 'Chi3 Protocol',
    decimals: 18,
    logoURI: '/src/assets/tokens/CHI3.svg',
    chainId: 1,
  },
  {
    symbol: 'PSI3',
    name: 'Psi3 Protocol',
    decimals: 18,
    logoURI: '/src/assets/tokens/PSI3.svg',
    chainId: 1,
  },
  {
    symbol: 'OMEGA3',
    name: 'Omega3 Protocol',
    decimals: 18,
    logoURI: '/src/assets/tokens/OMEGA3.svg',
    chainId: 1,
  },
  {
    symbol: 'SIGMA3',
    name: 'Sigma3 Protocol',
    decimals: 18,
    logoURI: '/src/assets/tokens/SIGMA3.svg',
    chainId: 1,
  },
  {
    symbol: 'TAU3',
    name: 'Tau3 Protocol',
    decimals: 18,
    logoURI: '/src/assets/tokens/TAU3.svg',
    chainId: 1,
  },
  {
    symbol: 'UPSILON3',
    name: 'Upsilon3 Protocol',
    decimals: 18,
    logoURI: '/src/assets/tokens/UPSILON3.svg',
    chainId: 1,
  },
  {
    symbol: 'PHI4',
    name: 'Phi4 Protocol',
    decimals: 18,
    logoURI: '/src/assets/tokens/PHI4.svg',
    chainId: 1,
  },
  {
    symbol: 'CHI4',
    name: 'Chi4 Protocol',
    decimals: 18,
    logoURI: '/src/assets/tokens/CHI4.svg',
    chainId: 1,
  },
  {
    symbol: 'PSI4',
    name: 'Psi4 Protocol',
    decimals: 18,
    logoURI: '/src/assets/tokens/PSI4.svg',
    chainId: 1,
  },
  {
    symbol: 'OMEGA4',
    name: 'Omega4 Protocol',
    decimals: 18,
    logoURI: '/src/assets/tokens/OMEGA4.svg',
    chainId: 1,
  },
  {
    symbol: 'SIGMA4',
    name: 'Sigma4 Protocol',
    decimals: 18,
    logoURI: '/src/assets/tokens/SIGMA4.svg',
    chainId: 1,
  },
  {
    symbol: 'TAU4',
    name: 'Tau4 Protocol',
    decimals: 18,
    logoURI: '/src/assets/tokens/TAU4.svg',
    chainId: 1,
  },
  {
    symbol: 'UPSILON4',
    name: 'Upsilon4 Protocol',
    decimals: 18,
    logoURI: '/src/assets/tokens/UPSILON4.svg',
    chainId: 1,
  },
  {
    symbol: 'PHI5',
    name: 'Phi5 Protocol',
    decimals: 18,
    logoURI: '/src/assets/tokens/PHI5.svg',
    chainId: 1,
  },
  {
    symbol: 'CHI5',
    name: 'Chi5 Protocol',
    decimals: 18,
    logoURI: '/src/assets/tokens/CHI5.svg',
    chainId: 1,
  },
  {
    symbol: 'PSI5',
    name: 'Psi5 Protocol',
    decimals: 18,
    logoURI: '/src/assets/tokens/PSI5.svg',
    chainId: 1,
  },
  {
    symbol: 'OMEGA5',
    name: 'Omega5 Protocol',
    decimals: 18,
    logoURI: '/src/assets/tokens/OMEGA5.svg',
    chainId: 1,
  },
  {
    symbol: 'SIGMA5',
    name: 'Sigma5 Protocol',
    decimals: 18,
    logoURI: '/src/assets/tokens/SIGMA5.svg',
    chainId: 1,
  },
  {
    symbol: 'TAU5',
    name: 'Tau5 Protocol',
    decimals: 18,
    logoURI: '/src/assets/tokens/TAU5.svg',
    chainId: 1,
  },
  {
    symbol: 'UPSILON5',
    name: 'Upsilon5 Protocol',
    decimals: 18,
    logoURI: '/src/assets/tokens/UPSILON5.svg',
    chainId: 1,
  },
];

// Default swap settings
export const DEFAULT_SLIPPAGE = 0.5; // 0.5%
export const DEFAULT_DEADLINE = 20; // 20 minutes
export const MIN_SLIPPAGE = 0.1;
export const MAX_SLIPPAGE = 50;
export const MIN_DEADLINE = 1;
export const MAX_DEADLINE = 4320; // 3 days

// Price impact thresholds
export const PRICE_IMPACT_WARNING = 3; // 3%
export const PRICE_IMPACT_ERROR = 5; // 5%

// Swap limits
export const MIN_SWAP_AMOUNT = 0.000001;
export const MAX_SWAP_AMOUNT = 1000000;
