import type { Token } from '../types';

// Helper function to get token icon URL
const getTokenIcon = (symbol: string): string => {
  // Map symbols to actual file names
  const iconMap: Record<string, string> = {
    'ETH': 'ETH.svg',
    'USDC': 'USDC.svg',
    'USDT': 'USDT.svg',
    'WBTC': 'WBTC.svg',
    'ATOM': 'ATOM.svg',
    'OSMO': 'OSMO.svg',
    'LUNA': 'LUNA.svg',
    'KUJI': 'KUJI.svg',
    'EVMOS': 'EVMOS.svg',
    'STRD': 'STRD.svg',
    'IBCX': 'IBCX.svg',
    'IRIS': 'IRIS.svg',
    'RATOM': 'rATOM.svg',
    'STATOM': 'stATOM.svg',
    'STLUNA': 'stLUNA.svg',
    'STOSMO': 'stOSMO.svg',
    'STEVMOS': 'stEVMOS.svg',
    'ampLUNA': 'ampLUNA.svg',
    'axlUSDC': 'axlUSDC.svg',
    'rSWTH': 'rSWTH.svg',
    'LSI': 'LSI.svg',
    'OKB': 'OKB.svg',
    'OKT': 'OKT.svg',
    'SWTH': 'SWTH.svg',
    'USC': 'USC.svg',
    'wstETH': 'wstETH.svg',
    'YieldUSD': 'YieldUSD.svg',
    'ZIL': 'ZIL.svg',
    'BLUR': 'BLUR.svg',
    'bNEO': 'bNEO.svg',
    'BUSD': 'BUSD.svg',
    'GMX': 'GMX.svg',
    'AAVE': 'AAVE.svg',
    'UNI': 'UNI.svg',
    'LINK': 'LINK.svg',
    'MATIC': 'MATIC.svg',
    'AVAX': 'AVAX.svg',
    'SOL': 'SOL.svg',
    'DOT': 'DOT.svg',
    'ADA': 'ADA.svg',
    'XRP': 'XRP.svg',
    'DOGE': 'DOGE.svg',
    'SHIB': 'SHIB.svg',
    'LTC': 'LTC.svg',
    'BCH': 'BCH.svg',
    'ALGO': 'ALGO.svg',
    'VET': 'VET.svg',
    'FIL': 'FIL.svg',
    'TRX': 'TRX.svg',
    'EOS': 'EOS.svg',
    'XLM': 'XLM.svg',
    'XTZ': 'XTZ.svg',
    'NEO': 'NEO.svg',
    'IOTA': 'MIOTA.svg', // Map IOTA to MIOTA
    'DASH': 'DASH.svg',
    'ZEC': 'ZEC.svg',
    'COMP': 'COMP.svg',
    'MKR': 'MKR.svg',
    'SNX': 'SNX.svg',
    'YFI': 'YFI.svg',
    'SUSHI': 'SUSHI.svg',
    'CRV': 'CRV.svg',
    '1INCH': '1INCH.svg',
    'BAL': 'BAL.svg',
    'LRC': 'LRC.svg',
    'ZRX': 'ZRX.svg',
    'BAT': 'BAT.svg',
    'ENJ': 'ENJ.svg',
    'MANA': 'MANA.svg',
    'SAND': 'SAND.svg',
    'AXS': 'AXS.svg',
    'CHZ': 'CHZ.svg',
    'FLOW': 'FLOW.svg',
    'ICP': 'ICP.svg',
    'THETA': 'THETA.svg',
    'FTM': 'FTM.svg',
    'NEAR': 'NEAR.svg',
    'HBAR': 'HBAR.svg',
    'EGLD': 'eGLD.svg', // Map EGLD to eGLD
    'KLAY': 'KLAY.svg',
    'FTT': 'FTT.svg',
    'CRO': 'CRO.svg',
    'KCS': 'KCS.svg',
    'HT': 'HT.svg',
    'LEO': 'LEO.svg',
    'GT': 'GT.svg',
    'BNB': 'BNB.svg',
    'CAKE': 'CAKE.svg',
    'BAKE': 'BAKE.svg',
    'AUTO': 'AUT.svg', // Map AUTO to AUT
    'ALPHA': 'ALPHA.svg',
    'BAND': 'BAND.svg',
    'KAVA': 'KAVA.svg',
    'RUNE': 'RUNE.svg',
    'ROSE': 'ROSE.svg',
    'SCRT': 'SCRT.svg',
    'JUNO': 'JUNO.svg',
    'STARS': 'STARS.svg',
    'REGEN': 'REGEN.svg',
    'AKASH': 'AKT.svg', // Map AKASH to AKT
    'SENT': 'DVPN.svg', // Map SENT to DVPN
    'FET': 'FET.svg',
    'PERSISTENCE': 'XPRT.svg', // Map PERSISTENCE to XPRT
    'CRYPTO': 'CRO.svg', // Map CRYPTO to CRO
    'CEL': 'CEL.svg',
    'NEXO': 'NEXO.svg',
    'COMPOUND': 'COMP.svg', // Map COMPOUND to COMP
    'UMA': 'UMA.svg',
    'REN': 'REN.svg',
    'KNC': 'KNC.svg',
    'REP': 'REP.svg',
    'LEND': 'LEND.svg',
    'KEEP': 'KEEP.svg',
    'NU': 'NU.svg',
    'STORJ': 'STORJ.svg',
    'GNO': 'GNO.svg',
    'ANT': 'ANT.svg',
    'MLN': 'MLN.svg',
    'DGX': 'DGX.svg',
    'DAI': 'DAI.svg',
    'SAI': 'SAI.svg',
    'USDS': 'USDS.svg',
    'TUSD': 'TUSD.svg',
    'GUSD': 'GUSD.svg',
    'PAX': 'PAX.svg',
    'HUSD': 'HUSD.svg',
    'USDN': 'USDN.svg',
    'RSV': 'RSV.svg',
    'FRAX': 'FRAX.svg',
    'LUSD': 'LUSD.svg',
    'FEI': 'FEI.svg',
    'TRIBE': 'TRIBE.svg',
    'RAI': 'RAI.svg',
    'ALUSD': 'ALUSD.svg',
    'DOLA': 'DOLA.svg',
    'OHM': 'OHM.svg',
    'SPELL': 'SPELL.svg',
    'MIM': 'MIM.svg',
    'CVX': 'CVX.svg',
    'FXS': 'FXS.svg',
    'LQTY': 'LQTY.svg',
    'ALCX': 'ALCX.svg',
    'TOKE': 'TOKE.svg',
    'BTRFLY': 'BTRFLY.svg',
    'PENDLE': 'PENDLE.svg',
    'ANGLE': 'ANGLE.svg',
    'FARM': 'FARM.svg',
    'PICKLE': 'PICKLE.svg',
    'CREAM': 'CREAM.svg',
    'BETA': 'BETA.svg',
    'GAMMA': 'GAMMA.svg',
    'DELTA': 'DELTA.svg',
    'LAMBDA': 'LAMBDA.svg',
    'SIGMA': 'SIGMA.svg',
    'OMEGA': 'OMEGA.svg',
    'PHI': 'PHI.svg',
    'PSI': 'PSI.svg',
    'CHI': 'CHI.svg',
    'XI': 'XI.svg',
    'RHO': 'RHO.svg',
    'TAU': 'TAU.svg',
    'UPSILON': 'UPSILON.svg',
    'PHI2': 'PHI2.svg',
    'CHI2': 'CHI2.svg',
    'PSI2': 'PSI2.svg',
    'OMEGA2': 'OMEGA2.svg',
    'SIGMA2': 'SIGMA2.svg',
    'TAU2': 'TAU2.svg',
    'UPSILON2': 'UPSILON2.svg',
    'PHI3': 'PHI3.svg',
    'CHI3': 'CHI3.svg',
    'PSI3': 'PSI3.svg',
    'OMEGA3': 'OMEGA3.svg',
    'SIGMA3': 'SIGMA3.svg',
    'TAU3': 'TAU3.svg',
    'UPSILON3': 'UPSILON3.svg',
    'PHI4': 'PHI4.svg',
    'CHI4': 'CHI4.svg',
    'PSI4': 'PSI4.svg',
    'OMEGA4': 'OMEGA4.svg',
    'SIGMA4': 'SIGMA4.svg',
    'TAU4': 'TAU4.svg',
    'UPSILON4': 'UPSILON4.svg',
    'PHI5': 'PHI5.svg',
    'CHI5': 'CHI5.svg',
    'PSI5': 'PSI5.svg',
    'OMEGA5': 'OMEGA5.svg',
    'SIGMA5': 'SIGMA5.svg',
    'TAU5': 'TAU5.svg',
    'UPSILON5': 'UPSILON5.svg',
  };

  const fileName = iconMap[symbol] || `${symbol}.svg`;
  // Use dynamic import for production builds
  return new URL(`../assets/tokens/${fileName}`, import.meta.url).href;
};

// Popular tokens with their metadata
export const POPULAR_TOKENS: Token[] = [
  {
    symbol: 'ETH',
    name: 'Ethereum',
    decimals: 18,
    logoURI: getTokenIcon('ETH'),
    chainId: 1,
  },
  {
    symbol: 'USDC',
    name: 'USD Coin',
    decimals: 6,
    logoURI: getTokenIcon('USDC'),
    chainId: 1,
  },
  {
    symbol: 'USDT',
    name: 'Tether USD',
    decimals: 6,
    logoURI: getTokenIcon('USDT'),
    chainId: 1,
  },
  {
    symbol: 'WBTC',
    name: 'Wrapped Bitcoin',
    decimals: 8,
    logoURI: getTokenIcon('WBTC'),
    chainId: 1,
  },
  {
    symbol: 'ATOM',
    name: 'Cosmos',
    decimals: 6,
    logoURI: getTokenIcon('ATOM'),
    chainId: 1,
  },
  {
    symbol: 'OSMO',
    name: 'Osmosis',
    decimals: 6,
    logoURI: getTokenIcon('OSMO'),
    chainId: 1,
  },
  {
    symbol: 'LUNA',
    name: 'Terra',
    decimals: 6,
    logoURI: getTokenIcon('LUNA'),
    chainId: 1,
  },
  {
    symbol: 'KUJI',
    name: 'Kujira',
    decimals: 6,
    logoURI: getTokenIcon('KUJI'),
    chainId: 1,
  },
  {
    symbol: 'EVMOS',
    name: 'Evmos',
    decimals: 18,
    logoURI: getTokenIcon('EVMOS'),
    chainId: 1,
  },
  {
    symbol: 'STRD',
    name: 'Stride',
    decimals: 6,
    logoURI: getTokenIcon('STRD'),
    chainId: 1,
  },
  {
    symbol: 'IBCX',
    name: 'IBCX',
    decimals: 6,
    logoURI: getTokenIcon('IBCX'),
    chainId: 1,
  },
  {
    symbol: 'IRIS',
    name: 'IRISnet',
    decimals: 6,
    logoURI: getTokenIcon('IRIS'),
    chainId: 1,
  },
  {
    symbol: 'RATOM',
    name: 'RATOM',
    decimals: 6,
    logoURI: getTokenIcon('RATOM'),
    chainId: 1,
  },
  {
    symbol: 'STATOM',
    name: 'stATOM',
    decimals: 6,
    logoURI: getTokenIcon('STATOM'),
    chainId: 1,
  },
  {
    symbol: 'STLUNA',
    name: 'stLUNA',
    decimals: 6,
    logoURI: getTokenIcon('STLUNA'),
    chainId: 1,
  },
  {
    symbol: 'STOSMO',
    name: 'stOSMO',
    decimals: 6,
    logoURI: getTokenIcon('STOSMO'),
    chainId: 1,
  },
  {
    symbol: 'STEVMOS',
    name: 'stEVMOS',
    decimals: 18,
    logoURI: getTokenIcon('STEVMOS'),
    chainId: 1,
  },
  {
    symbol: 'ampLUNA',
    name: 'ampLUNA',
    decimals: 6,
    logoURI: getTokenIcon('ampLUNA'),
    chainId: 1,
  },
  {
    symbol: 'axlUSDC',
    name: 'Axelar USDC',
    decimals: 6,
    logoURI: getTokenIcon('axlUSDC'),
    chainId: 1,
  },
  {
    symbol: 'rSWTH',
    name: 'rSWTH',
    decimals: 8,
    logoURI: getTokenIcon('rSWTH'),
    chainId: 1,
  },
  {
    symbol: 'LSI',
    name: 'Liquid Staking Index',
    decimals: 6,
    logoURI: getTokenIcon('LSI'),
    chainId: 1,
  },
  {
    symbol: 'OKB',
    name: 'OKB',
    decimals: 18,
    logoURI: getTokenIcon('OKB'),
    chainId: 1,
  },
  {
    symbol: 'OKT',
    name: 'OKT',
    decimals: 18,
    logoURI: getTokenIcon('OKT'),
    chainId: 1,
  },
  {
    symbol: 'SWTH',
    name: 'Switcheo',
    decimals: 8,
    logoURI: getTokenIcon('SWTH'),
    chainId: 1,
  },
  {
    symbol: 'USC',
    name: 'USC',
    decimals: 6,
    logoURI: getTokenIcon('USC'),
    chainId: 1,
  },
  {
    symbol: 'wstETH',
    name: 'Wrapped stETH',
    decimals: 18,
    logoURI: getTokenIcon('wstETH'),
    chainId: 1,
  },
  {
    symbol: 'YieldUSD',
    name: 'YieldUSD',
    decimals: 6,
    logoURI: getTokenIcon('YieldUSD'),
    chainId: 1,
  },
  {
    symbol: 'ZIL',
    name: 'Zilliqa',
    decimals: 12,
    logoURI: getTokenIcon('ZIL'),
    chainId: 1,
  },
  {
    symbol: 'BLUR',
    name: 'Blur',
    decimals: 18,
    logoURI: getTokenIcon('BLUR'),
    chainId: 1,
  },
  {
    symbol: 'bNEO',
    name: 'bNEO',
    decimals: 8,
    logoURI: getTokenIcon('bNEO'),
    chainId: 1,
  },
  {
    symbol: 'BUSD',
    name: 'Binance USD',
    decimals: 18,
    logoURI: getTokenIcon('BUSD'),
    chainId: 1,
  },
  {
    symbol: 'GMX',
    name: 'GMX',
    decimals: 18,
    logoURI: getTokenIcon('GMX'),
    chainId: 1,
  },
  // Additional tokens for infinite scroll demo
  {
    symbol: 'AAVE',
    name: 'Aave Token',
    decimals: 18,
    logoURI: getTokenIcon('AAVE'),
    chainId: 1,
  },
  {
    symbol: 'UNI',
    name: 'Uniswap',
    decimals: 18,
    logoURI: getTokenIcon('UNI'),
    chainId: 1,
  },
  {
    symbol: 'LINK',
    name: 'Chainlink',
    decimals: 18,
    logoURI: getTokenIcon('LINK'),
    chainId: 1,
  },
  {
    symbol: 'MATIC',
    name: 'Polygon',
    decimals: 18,
    logoURI: getTokenIcon('MATIC'),
    chainId: 1,
  },
  {
    symbol: 'AVAX',
    name: 'Avalanche',
    decimals: 18,
    logoURI: getTokenIcon('AVAX'),
    chainId: 1,
  },
  {
    symbol: 'SOL',
    name: 'Solana',
    decimals: 9,
    logoURI: getTokenIcon('SOL'),
    chainId: 1,
  },
  {
    symbol: 'DOT',
    name: 'Polkadot',
    decimals: 10,
    logoURI: getTokenIcon('DOT'),
    chainId: 1,
  },
  {
    symbol: 'ADA',
    name: 'Cardano',
    decimals: 6,
    logoURI: getTokenIcon('ADA'),
    chainId: 1,
  },
  {
    symbol: 'XRP',
    name: 'Ripple',
    decimals: 6,
    logoURI: getTokenIcon('XRP'),
    chainId: 1,
  },
  {
    symbol: 'DOGE',
    name: 'Dogecoin',
    decimals: 8,
    logoURI: getTokenIcon('DOGE'),
    chainId: 1,
  },
  {
    symbol: 'SHIB',
    name: 'Shiba Inu',
    decimals: 18,
    logoURI: getTokenIcon('SHIB'),
    chainId: 1,
  },
  {
    symbol: 'LTC',
    name: 'Litecoin',
    decimals: 8,
    logoURI: getTokenIcon('LTC'),
    chainId: 1,
  },
  {
    symbol: 'BCH',
    name: 'Bitcoin Cash',
    decimals: 8,
    logoURI: getTokenIcon('BCH'),
    chainId: 1,
  },
  {
    symbol: 'ALGO',
    name: 'Algorand',
    decimals: 6,
    logoURI: getTokenIcon('ALGO'),
    chainId: 1,
  },
  {
    symbol: 'VET',
    name: 'VeChain',
    decimals: 18,
    logoURI: getTokenIcon('VET'),
    chainId: 1,
  },
  {
    symbol: 'FIL',
    name: 'Filecoin',
    decimals: 18,
    logoURI: getTokenIcon('FIL'),
    chainId: 1,
  },
  {
    symbol: 'TRX',
    name: 'TRON',
    decimals: 6,
    logoURI: getTokenIcon('TRX'),
    chainId: 1,
  },
  {
    symbol: 'EOS',
    name: 'EOS',
    decimals: 4,
    logoURI: getTokenIcon('EOS'),
    chainId: 1,
  },
  {
    symbol: 'XLM',
    name: 'Stellar',
    decimals: 7,
    logoURI: getTokenIcon('XLM'),
    chainId: 1,
  },
  {
    symbol: 'XTZ',
    name: 'Tezos',
    decimals: 6,
    logoURI: getTokenIcon('XTZ'),
    chainId: 1,
  },
  {
    symbol: 'NEO',
    name: 'NEO',
    decimals: 8,
    logoURI: getTokenIcon('NEO'),
    chainId: 1,
  },
  {
    symbol: 'IOTA',
    name: 'IOTA',
    decimals: 6,
    logoURI: getTokenIcon('IOTA'),
    chainId: 1,
  },
  {
    symbol: 'DASH',
    name: 'Dash',
    decimals: 8,
    logoURI: getTokenIcon('DASH'),
    chainId: 1,
  },
  {
    symbol: 'ZEC',
    name: 'Zcash',
    decimals: 8,
    logoURI: getTokenIcon('ZEC'),
    chainId: 1,
  },
  {
    symbol: 'COMP',
    name: 'Compound',
    decimals: 18,
    logoURI: getTokenIcon('COMP'),
    chainId: 1,
  },
  {
    symbol: 'MKR',
    name: 'Maker',
    decimals: 18,
    logoURI: getTokenIcon('MKR'),
    chainId: 1,
  },
  {
    symbol: 'SNX',
    name: 'Synthetix',
    decimals: 18,
    logoURI: getTokenIcon('SNX'),
    chainId: 1,
  },
  {
    symbol: 'YFI',
    name: 'Yearn Finance',
    decimals: 18,
    logoURI: getTokenIcon('YFI'),
    chainId: 1,
  },
  {
    symbol: 'SUSHI',
    name: 'SushiSwap',
    decimals: 18,
    logoURI: getTokenIcon('SUSHI'),
    chainId: 1,
  },
  {
    symbol: 'CRV',
    name: 'Curve DAO Token',
    decimals: 18,
    logoURI: getTokenIcon('CRV'),
    chainId: 1,
  },
  {
    symbol: '1INCH',
    name: '1inch',
    decimals: 18,
    logoURI: getTokenIcon('1INCH'),
    chainId: 1,
  },
  {
    symbol: 'BAL',
    name: 'Balancer',
    decimals: 18,
    logoURI: getTokenIcon('BAL'),
    chainId: 1,
  },
  {
    symbol: 'LRC',
    name: 'Loopring',
    decimals: 18,
    logoURI: getTokenIcon('LRC'),
    chainId: 1,
  },
  {
    symbol: 'ZRX',
    name: '0x Protocol',
    decimals: 18,
    logoURI: getTokenIcon('ZRX'),
    chainId: 1,
  },
  {
    symbol: 'BAT',
    name: 'Basic Attention Token',
    decimals: 18,
    logoURI: getTokenIcon('BAT'),
    chainId: 1,
  },
  {
    symbol: 'ENJ',
    name: 'Enjin Coin',
    decimals: 18,
    logoURI: getTokenIcon('ENJ'),
    chainId: 1,
  },
  {
    symbol: 'MANA',
    name: 'Decentraland',
    decimals: 18,
    logoURI: getTokenIcon('MANA'),
    chainId: 1,
  },
  {
    symbol: 'SAND',
    name: 'The Sandbox',
    decimals: 18,
    logoURI: getTokenIcon('SAND'),
    chainId: 1,
  },
  {
    symbol: 'AXS',
    name: 'Axie Infinity',
    decimals: 18,
    logoURI: getTokenIcon('AXS'),
    chainId: 1,
  },
  {
    symbol: 'CHZ',
    name: 'Chiliz',
    decimals: 18,
    logoURI: getTokenIcon('CHZ'),
    chainId: 1,
  },
  {
    symbol: 'FLOW',
    name: 'Flow',
    decimals: 8,
    logoURI: getTokenIcon('FLOW'),
    chainId: 1,
  },
  {
    symbol: 'ICP',
    name: 'Internet Computer',
    decimals: 8,
    logoURI: getTokenIcon('ICP'),
    chainId: 1,
  },
  {
    symbol: 'THETA',
    name: 'Theta Network',
    decimals: 18,
    logoURI: getTokenIcon('THETA'),
    chainId: 1,
  },
  {
    symbol: 'FTM',
    name: 'Fantom',
    decimals: 18,
    logoURI: getTokenIcon('FTM'),
    chainId: 1,
  },
  {
    symbol: 'NEAR',
    name: 'NEAR Protocol',
    decimals: 24,
    logoURI: getTokenIcon('NEAR'),
    chainId: 1,
  },
  {
    symbol: 'HBAR',
    name: 'Hedera',
    decimals: 8,
    logoURI: getTokenIcon('HBAR'),
    chainId: 1,
  },
  {
    symbol: 'EGLD',
    name: 'MultiversX',
    decimals: 18,
    logoURI: getTokenIcon('EGLD'),
    chainId: 1,
  },
  {
    symbol: 'KLAY',
    name: 'Klaytn',
    decimals: 18,
    logoURI: getTokenIcon('KLAY'),
    chainId: 1,
  },
  {
    symbol: 'FTT',
    name: 'FTX Token',
    decimals: 18,
    logoURI: getTokenIcon('FTT'),
    chainId: 1,
  },
  {
    symbol: 'CRO',
    name: 'Cronos',
    decimals: 8,
    logoURI: getTokenIcon('CRO'),
    chainId: 1,
  },
  {
    symbol: 'KCS',
    name: 'KuCoin Token',
    decimals: 6,
    logoURI: getTokenIcon('KCS'),
    chainId: 1,
  },
  {
    symbol: 'HT',
    name: 'Huobi Token',
    decimals: 18,
    logoURI: getTokenIcon('HT'),
    chainId: 1,
  },
  {
    symbol: 'LEO',
    name: 'LEO Token',
    decimals: 18,
    logoURI: getTokenIcon('LEO'),
    chainId: 1,
  },
  {
    symbol: 'GT',
    name: 'GateToken',
    decimals: 18,
    logoURI: getTokenIcon('GT'),
    chainId: 1,
  },
  {
    symbol: 'BNB',
    name: 'BNB',
    decimals: 18,
    logoURI: getTokenIcon('BNB'),
    chainId: 1,
  },
  {
    symbol: 'CAKE',
    name: 'PancakeSwap',
    decimals: 18,
    logoURI: getTokenIcon('CAKE'),
    chainId: 1,
  },
  {
    symbol: 'BAKE',
    name: 'BakeryToken',
    decimals: 18,
    logoURI: getTokenIcon('BAKE'),
    chainId: 1,
  },
  {
    symbol: 'AUTO',
    name: 'AutoFarm',
    decimals: 18,
    logoURI: getTokenIcon('AUTO'),
    chainId: 1,
  },
  {
    symbol: 'ALPHA',
    name: 'Alpha Finance',
    decimals: 18,
    logoURI: getTokenIcon('ALPHA'),
    chainId: 1,
  },
  {
    symbol: 'BAND',
    name: 'Band Protocol',
    decimals: 18,
    logoURI: getTokenIcon('BAND'),
    chainId: 1,
  },
  {
    symbol: 'KAVA',
    name: 'Kava',
    decimals: 6,
    logoURI: getTokenIcon('KAVA'),
    chainId: 1,
  },
  {
    symbol: 'RUNE',
    name: 'THORChain',
    decimals: 8,
    logoURI: getTokenIcon('RUNE'),
    chainId: 1,
  },
  {
    symbol: 'ROSE',
    name: 'Oasis Network',
    decimals: 8,
    logoURI: getTokenIcon('ROSE'),
    chainId: 1,
  },
  {
    symbol: 'SCRT',
    name: 'Secret Network',
    decimals: 6,
    logoURI: getTokenIcon('SCRT'),
    chainId: 1,
  },
  {
    symbol: 'JUNO',
    name: 'Juno Network',
    decimals: 6,
    logoURI: getTokenIcon('JUNO'),
    chainId: 1,
  },
  {
    symbol: 'STARS',
    name: 'Stargaze',
    decimals: 6,
    logoURI: getTokenIcon('STARS'),
    chainId: 1,
  },
  {
    symbol: 'REGEN',
    name: 'Regen Network',
    decimals: 6,
    logoURI: getTokenIcon('REGEN'),
    chainId: 1,
  },
  {
    symbol: 'AKASH',
    name: 'Akash Network',
    decimals: 6,
    logoURI: getTokenIcon('AKASH'),
    chainId: 1,
  },
  {
    symbol: 'SENT',
    name: 'Sentinel',
    decimals: 6,
    logoURI: getTokenIcon('SENT'),
    chainId: 1,
  },
  {
    symbol: 'FET',
    name: 'Fetch.ai',
    decimals: 18,
    logoURI: getTokenIcon('FET'),
    chainId: 1,
  },
  {
    symbol: 'PERSISTENCE',
    name: 'Persistence',
    decimals: 6,
    logoURI: getTokenIcon('PERSISTENCE'),
    chainId: 1,
  },
  {
    symbol: 'CRYPTO',
    name: 'Crypto.com Coin',
    decimals: 8,
    logoURI: getTokenIcon('CRYPTO'),
    chainId: 1,
  },
  {
    symbol: 'CEL',
    name: 'Celsius',
    decimals: 4,
    logoURI: getTokenIcon('CEL'),
    chainId: 1,
  },
  {
    symbol: 'NEXO',
    name: 'NEXO',
    decimals: 18,
    logoURI: getTokenIcon('NEXO'),
    chainId: 1,
  },
  {
    symbol: 'COMPOUND',
    name: 'Compound',
    decimals: 18,
    logoURI: getTokenIcon('COMPOUND'),
    chainId: 1,
  },
  {
    symbol: 'UMA',
    name: 'UMA',
    decimals: 18,
    logoURI: getTokenIcon('UMA'),
    chainId: 1,
  },
  {
    symbol: 'REN',
    name: 'Ren',
    decimals: 18,
    logoURI: getTokenIcon('REN'),
    chainId: 1,
  },
  {
    symbol: 'KNC',
    name: 'Kyber Network',
    decimals: 18,
    logoURI: getTokenIcon('KNC'),
    chainId: 1,
  },
  {
    symbol: 'REP',
    name: 'Augur',
    decimals: 18,
    logoURI: getTokenIcon('REP'),
    chainId: 1,
  },
  {
    symbol: 'LEND',
    name: 'Aave LEND',
    decimals: 18,
    logoURI: getTokenIcon('LEND'),
    chainId: 1,
  },
  {
    symbol: 'KEEP',
    name: 'Keep Network',
    decimals: 18,
    logoURI: getTokenIcon('KEEP'),
    chainId: 1,
  },
  {
    symbol: 'NU',
    name: 'NuCypher',
    decimals: 18,
    logoURI: getTokenIcon('NU'),
    chainId: 1,
  },
  {
    symbol: 'STORJ',
    name: 'Storj',
    decimals: 8,
    logoURI: getTokenIcon('STORJ'),
    chainId: 1,
  },
  {
    symbol: 'GNO',
    name: 'Gnosis',
    decimals: 18,
    logoURI: getTokenIcon('GNO'),
    chainId: 1,
  },
  {
    symbol: 'ANT',
    name: 'Aragon',
    decimals: 18,
    logoURI: getTokenIcon('ANT'),
    chainId: 1,
  },
  {
    symbol: 'MLN',
    name: 'Melon',
    decimals: 18,
    logoURI: getTokenIcon('MLN'),
    chainId: 1,
  },
  {
    symbol: 'DGX',
    name: 'Digix Gold',
    decimals: 9,
    logoURI: getTokenIcon('DGX'),
    chainId: 1,
  },
  {
    symbol: 'MKR',
    name: 'Maker',
    decimals: 18,
    logoURI: getTokenIcon('MKR'),
    chainId: 1,
  },
  {
    symbol: 'DAI',
    name: 'Dai Stablecoin',
    decimals: 18,
    logoURI: getTokenIcon('DAI'),
    chainId: 1,
  },
  {
    symbol: 'SAI',
    name: 'Sai Stablecoin',
    decimals: 18,
    logoURI: getTokenIcon('SAI'),
    chainId: 1,
  },
  {
    symbol: 'USDS',
    name: 'USD//C',
    decimals: 6,
    logoURI: getTokenIcon('USDS'),
    chainId: 1,
  },
  {
    symbol: 'TUSD',
    name: 'TrueUSD',
    decimals: 18,
    logoURI: getTokenIcon('TUSD'),
    chainId: 1,
  },
  {
    symbol: 'GUSD',
    name: 'Gemini Dollar',
    decimals: 2,
    logoURI: getTokenIcon('GUSD'),
    chainId: 1,
  },
  {
    symbol: 'PAX',
    name: 'Paxos Standard',
    decimals: 18,
    logoURI: getTokenIcon('PAX'),
    chainId: 1,
  },
  {
    symbol: 'BUSD',
    name: 'Binance USD',
    decimals: 18,
    logoURI: getTokenIcon('BUSD'),
    chainId: 1,
  },
  {
    symbol: 'HUSD',
    name: 'HUSD',
    decimals: 8,
    logoURI: getTokenIcon('HUSD'),
    chainId: 1,
  },
  {
    symbol: 'USDN',
    name: 'Neutrino USD',
    decimals: 6,
    logoURI: getTokenIcon('USDN'),
    chainId: 1,
  },
  {
    symbol: 'RSV',
    name: 'Reserve',
    decimals: 18,
    logoURI: getTokenIcon('RSV'),
    chainId: 1,
  },
  {
    symbol: 'FRAX',
    name: 'Frax',
    decimals: 18,
    logoURI: getTokenIcon('FRAX'),
    chainId: 1,
  },
  {
    symbol: 'LUSD',
    name: 'Liquity USD',
    decimals: 18,
    logoURI: getTokenIcon('LUSD'),
    chainId: 1,
  },
  {
    symbol: 'FEI',
    name: 'Fei USD',
    decimals: 18,
    logoURI: getTokenIcon('FEI'),
    chainId: 1,
  },
  {
    symbol: 'TRIBE',
    name: 'Tribe',
    decimals: 18,
    logoURI: getTokenIcon('TRIBE'),
    chainId: 1,
  },
  {
    symbol: 'RAI',
    name: 'Rai Reflex Index',
    decimals: 18,
    logoURI: getTokenIcon('RAI'),
    chainId: 1,
  },
  {
    symbol: 'ALUSD',
    name: 'Alchemix USD',
    decimals: 18,
    logoURI: getTokenIcon('ALUSD'),
    chainId: 1,
  },
  {
    symbol: 'DOLA',
    name: 'Dola USD Stablecoin',
    decimals: 18,
    logoURI: getTokenIcon('DOLA'),
    chainId: 1,
  },
  {
    symbol: 'OHM',
    name: 'Olympus',
    decimals: 9,
    logoURI: getTokenIcon('OHM'),
    chainId: 1,
  },
  {
    symbol: 'SPELL',
    name: 'Spell Token',
    decimals: 18,
    logoURI: getTokenIcon('SPELL'),
    chainId: 1,
  },
  {
    symbol: 'MIM',
    name: 'Magic Internet Money',
    decimals: 18,
    logoURI: getTokenIcon('MIM'),
    chainId: 1,
  },
  {
    symbol: 'CVX',
    name: 'Convex Finance',
    decimals: 18,
    logoURI: getTokenIcon('CVX'),
    chainId: 1,
  },
  {
    symbol: 'FXS',
    name: 'Frax Share',
    decimals: 18,
    logoURI: getTokenIcon('FXS'),
    chainId: 1,
  },
  {
    symbol: 'LQTY',
    name: 'Liquity',
    decimals: 18,
    logoURI: getTokenIcon('LQTY'),
    chainId: 1,
  },
  {
    symbol: 'ALCX',
    name: 'Alchemix',
    decimals: 18,
    logoURI: getTokenIcon('ALCX'),
    chainId: 1,
  },
  {
    symbol: 'TOKE',
    name: 'Tokemak',
    decimals: 18,
    logoURI: getTokenIcon('TOKE'),
    chainId: 1,
  },
  {
    symbol: 'BTRFLY',
    name: 'Redacted Cartel',
    decimals: 18,
    logoURI: getTokenIcon('BTRFLY'),
    chainId: 1,
  },
  {
    symbol: 'PENDLE',
    name: 'Pendle',
    decimals: 18,
    logoURI: getTokenIcon('PENDLE'),
    chainId: 1,
  },
  {
    symbol: 'ANGLE',
    name: 'Angle Protocol',
    decimals: 18,
    logoURI: getTokenIcon('ANGLE'),
    chainId: 1,
  },
  {
    symbol: 'FARM',
    name: 'Harvest Finance',
    decimals: 18,
    logoURI: getTokenIcon('FARM'),
    chainId: 1,
  },
  {
    symbol: 'PICKLE',
    name: 'Pickle Finance',
    decimals: 18,
    logoURI: getTokenIcon('PICKLE'),
    chainId: 1,
  },
  {
    symbol: 'CREAM',
    name: 'Cream Finance',
    decimals: 18,
    logoURI: getTokenIcon('CREAM'),
    chainId: 1,
  },
  {
    symbol: 'ALPHA',
    name: 'Alpha Homora',
    decimals: 18,
    logoURI: getTokenIcon('ALPHA'),
    chainId: 1,
  },
  {
    symbol: 'BETA',
    name: 'Beta Finance',
    decimals: 18,
    logoURI: getTokenIcon('BETA'),
    chainId: 1,
  },
  {
    symbol: 'GAMMA',
    name: 'Gamma Protocol',
    decimals: 18,
    logoURI: getTokenIcon('GAMMA'),
    chainId: 1,
  },
  {
    symbol: 'DELTA',
    name: 'Delta Protocol',
    decimals: 18,
    logoURI: getTokenIcon('DELTA'),
    chainId: 1,
  },
  {
    symbol: 'THETA',
    name: 'Theta Protocol',
    decimals: 18,
    logoURI: getTokenIcon('THETA'),
    chainId: 1,
  },
  {
    symbol: 'LAMBDA',
    name: 'Lambda Protocol',
    decimals: 18,
    logoURI: getTokenIcon('LAMBDA'),
    chainId: 1,
  },
  {
    symbol: 'SIGMA',
    name: 'Sigma Protocol',
    decimals: 18,
    logoURI: getTokenIcon('SIGMA'),
    chainId: 1,
  },
  {
    symbol: 'OMEGA',
    name: 'Omega Protocol',
    decimals: 18,
    logoURI: getTokenIcon('OMEGA'),
    chainId: 1,
  },
  {
    symbol: 'PHI',
    name: 'Phi Protocol',
    decimals: 18,
    logoURI: getTokenIcon('PHI'),
    chainId: 1,
  },
  {
    symbol: 'PSI',
    name: 'Psi Protocol',
    decimals: 18,
    logoURI: getTokenIcon('PSI'),
    chainId: 1,
  },
  {
    symbol: 'CHI',
    name: 'Chi Protocol',
    decimals: 18,
    logoURI: getTokenIcon('CHI'),
    chainId: 1,
  },
  {
    symbol: 'XI',
    name: 'Xi Protocol',
    decimals: 18,
    logoURI: getTokenIcon('XI'),
    chainId: 1,
  },
  {
    symbol: 'RHO',
    name: 'Rho Protocol',
    decimals: 18,
    logoURI: getTokenIcon('RHO'),
    chainId: 1,
  },
  {
    symbol: 'TAU',
    name: 'Tau Protocol',
    decimals: 18,
    logoURI: getTokenIcon('TAU'),
    chainId: 1,
  },
  {
    symbol: 'UPSILON',
    name: 'Upsilon Protocol',
    decimals: 18,
    logoURI: getTokenIcon('UPSILON'),
    chainId: 1,
  },
  {
    symbol: 'PHI2',
    name: 'Phi2 Protocol',
    decimals: 18,
    logoURI: getTokenIcon('PHI2'),
    chainId: 1,
  },
  {
    symbol: 'CHI2',
    name: 'Chi2 Protocol',
    decimals: 18,
    logoURI: getTokenIcon('CHI2'),
    chainId: 1,
  },
  {
    symbol: 'PSI2',
    name: 'Psi2 Protocol',
    decimals: 18,
    logoURI: getTokenIcon('PSI2'),
    chainId: 1,
  },
  {
    symbol: 'OMEGA2',
    name: 'Omega2 Protocol',
    decimals: 18,
    logoURI: getTokenIcon('OMEGA2'),
    chainId: 1,
  },
  {
    symbol: 'SIGMA2',
    name: 'Sigma2 Protocol',
    decimals: 18,
    logoURI: getTokenIcon('SIGMA2'),
    chainId: 1,
  },
  {
    symbol: 'TAU2',
    name: 'Tau2 Protocol',
    decimals: 18,
    logoURI: getTokenIcon('TAU2'),
    chainId: 1,
  },
  {
    symbol: 'UPSILON2',
    name: 'Upsilon2 Protocol',
    decimals: 18,
    logoURI: getTokenIcon('UPSILON2'),
    chainId: 1,
  },
  {
    symbol: 'PHI3',
    name: 'Phi3 Protocol',
    decimals: 18,
    logoURI: getTokenIcon('PHI3'),
    chainId: 1,
  },
  {
    symbol: 'CHI3',
    name: 'Chi3 Protocol',
    decimals: 18,
    logoURI: getTokenIcon('CHI3'),
    chainId: 1,
  },
  {
    symbol: 'PSI3',
    name: 'Psi3 Protocol',
    decimals: 18,
    logoURI: getTokenIcon('PSI3'),
    chainId: 1,
  },
  {
    symbol: 'OMEGA3',
    name: 'Omega3 Protocol',
    decimals: 18,
    logoURI: getTokenIcon('OMEGA3'),
    chainId: 1,
  },
  {
    symbol: 'SIGMA3',
    name: 'Sigma3 Protocol',
    decimals: 18,
    logoURI: getTokenIcon('SIGMA3'),
    chainId: 1,
  },
  {
    symbol: 'TAU3',
    name: 'Tau3 Protocol',
    decimals: 18,
    logoURI: getTokenIcon('TAU3'),
    chainId: 1,
  },
  {
    symbol: 'UPSILON3',
    name: 'Upsilon3 Protocol',
    decimals: 18,
    logoURI: getTokenIcon('UPSILON3'),
    chainId: 1,
  },
  {
    symbol: 'PHI4',
    name: 'Phi4 Protocol',
    decimals: 18,
    logoURI: getTokenIcon('PHI4'),
    chainId: 1,
  },
  {
    symbol: 'CHI4',
    name: 'Chi4 Protocol',
    decimals: 18,
    logoURI: getTokenIcon('CHI4'),
    chainId: 1,
  },
  {
    symbol: 'PSI4',
    name: 'Psi4 Protocol',
    decimals: 18,
    logoURI: getTokenIcon('PSI4'),
    chainId: 1,
  },
  {
    symbol: 'OMEGA4',
    name: 'Omega4 Protocol',
    decimals: 18,
    logoURI: getTokenIcon('OMEGA4'),
    chainId: 1,
  },
  {
    symbol: 'SIGMA4',
    name: 'Sigma4 Protocol',
    decimals: 18,
    logoURI: getTokenIcon('SIGMA4'),
    chainId: 1,
  },
  {
    symbol: 'TAU4',
    name: 'Tau4 Protocol',
    decimals: 18,
    logoURI: getTokenIcon('TAU4'),
    chainId: 1,
  },
  {
    symbol: 'UPSILON4',
    name: 'Upsilon4 Protocol',
    decimals: 18,
    logoURI: getTokenIcon('UPSILON4'),
    chainId: 1,
  },
  {
    symbol: 'PHI5',
    name: 'Phi5 Protocol',
    decimals: 18,
    logoURI: getTokenIcon('PHI5'),
    chainId: 1,
  },
  {
    symbol: 'CHI5',
    name: 'Chi5 Protocol',
    decimals: 18,
    logoURI: getTokenIcon('CHI5'),
    chainId: 1,
  },
  {
    symbol: 'PSI5',
    name: 'Psi5 Protocol',
    decimals: 18,
    logoURI: getTokenIcon('PSI5'),
    chainId: 1,
  },
  {
    symbol: 'OMEGA5',
    name: 'Omega5 Protocol',
    decimals: 18,
    logoURI: getTokenIcon('OMEGA5'),
    chainId: 1,
  },
  {
    symbol: 'SIGMA5',
    name: 'Sigma5 Protocol',
    decimals: 18,
    logoURI: getTokenIcon('SIGMA5'),
    chainId: 1,
  },
  {
    symbol: 'TAU5',
    name: 'Tau5 Protocol',
    decimals: 18,
    logoURI: getTokenIcon('TAU5'),
    chainId: 1,
  },
  {
    symbol: 'UPSILON5',
    name: 'Upsilon5 Protocol',
    decimals: 18,
    logoURI: getTokenIcon('UPSILON5'),
    chainId: 1,
  },
];

// Default swap settings
export const DEFAULT_SLIPPAGE = 0.5; // 0.5%
export const DEFAULT_DEADLINE = 20; // 20 minutes
export const MIN_SLIPPAGE = 0.1;
export const MAX_SLIPPAGE = 50;
export const MIN_DEADLINE = 1;
export const MAX_DEADLINE = 4320; // 3 days

// Price impact thresholds
export const PRICE_IMPACT_WARNING = 3; // 3%
export const PRICE_IMPACT_ERROR = 5; // 5%

// Swap limits
export const MIN_SWAP_AMOUNT = 0.000001;
export const MAX_SWAP_AMOUNT = 1000000;
